# Generated by Django 5.0.1 on 2024-02-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmpApp', '0003_emp_emp_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='emp_photo',
        ),
    ]
